# JWT
jwt.secret-key=413F4428472B4B6250655368566D5970337336763979244226452948404D6351

# Supabase
supabase.url=https://wbptqnvcpiorvwjotqwx.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndicHRxbnZjcGlvcnZ3am90cXd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNDE0MDcsImV4cCI6MjA1NTgxNzQwN30.VC8h-3JynU2mJghOlzKa8XSsKsrTchcCTKy1hdI6W6c
supabase.bucket.images=course-images
supabase.bucket.resources=course-resources

# Welcome message
welcome.message=Welcome from Config Server