# Server configuration
server.port=8081

# JWT
jwt.secret-key=413F4428472B4B6250655368566D5970337336763979244226452948404D6351

# Supabase
supabase.url=https://wbptqnvcpiorvwjotqwx.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
supabase.bucket.images=course-images
supabase.bucket.resources=course-resources

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/pi_work_ms?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Welcome message
welcome.message=Welcome from Config Server
